before_script:
  - apt-get update -y
  - apt-get install -y openjdk-17-jdk maven

stages:
  - compile
  - test
  - package

compile:
  stage: compile
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn package